[package]
name = "iced-todo"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
iced = "0.12.1"
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.122"
async-std = "1.12.0"
